name: Check and Build
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  release:
    types: [released]
permissions: read-all
jobs:
  build:
    name: Make pip packages
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the Git repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Install build tool
        run: pip install build
      - name: Building toltecmk
        run: python -m build --sdist
      - uses: actions/upload-artifact@v3
        with:
          name: pip
          path: dist/*
  publish:
    name: Publish to PyPi
    runs-on: ubuntu-20
    needs: [build]
    if: github.repository == 'Eeems-Org/python-liboxide' && github.event_name == 'release' && startsWith(github.ref, 'refs/tags')
    permissions:
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/p/liboxide
    steps:
      - name: Download pip packages
        id: download
        uses: action/download-artifact@v4
        with:
          name: pip
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: ${{ steps.download.outputs.download-path }}
